PANDAS

In [2]:
# instalar
%pip install pandas

Requirement already satisfied: pandas in c:\users\max\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\max\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\max\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\max\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\max\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\max\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# instalar
import pandas as pd

In [5]:
# lista
# Diccionar

data = [['Juan', 25], ['Pedro', 25], ['Luis', 25]]

print(data)

df = pd.DataFrame(data, columns = ['Nombre', 'Edad'])
df

[['Juan', 25], ['Pedro', 25], ['Luis', 25]]

  Nombre  Edad
0   Juan    25
1  Pedro    25
2   Luis    25

In [4]:
# Crear desde Diccionario
data = {
    'Nombre': ['Juan', 'Pedro', 'Luis'],
    'Edad': [25, 26, 25]
}

df_1 = pd.DataFrame(data)

df_1

  Nombre  Edad
0   Juan    25
1  Pedro    26
2   Luis    25

In [6]:
data = {
    'Nombre': ['Alexander', 'Franklin', 'Alberto'],
    'Edad': [28, 29, 55],
}

df_2 = pd.DataFrame(data)

df_2

      Nombre  Edad
0  Alexander    28
1   Franklin    29
2    Alberto    55

In [4]:
# Leer un archivo de una ruta indicada
df = pd.read_csv('utils/data/data.csv')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [6]:
# Leer un archivo sin extension y con un separador especial
df = pd.read_csv('utils/data/data', sep = '|')
df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [10]:
# Leer un archivo csv sin cabecera
df = pd.read_csv('utils/data/data_without_header',
                 sep = ',',
                 header= None,
                 names = ['Nombre', 'Edad', 'Ciudad']
                 )

df

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [23]:
# leer un archivo json

df = pd.read_json('utils/data/data.json')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [24]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

METODOS DATA FRAME

In [25]:
df.describe()

       edad
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [26]:
df.head()

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [27]:
df.tail(1)

  nombre  edad   ciudad
2  Pedro    35  Sevilla

In [28]:
df.columns

Index(['nombre', 'edad', 'ciudad'], dtype='object')

In [29]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [30]:
df.count()

nombre    3
edad      3
ciudad    3
dtype: int64

ACCEDER A LOS VALORES

In [31]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [32]:
df['ciudad']

#df[['ciudad', 'edad']]

0       Madrid
1    Barcelona
2      Sevilla
Name: ciudad, dtype: object

In [18]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [19]:
# Seleccionar una fila

print(df.loc[0])

# Multiples Lineas
print("### \n")
print(df.loc[[0, 2]])

# Filas que cumplie cierta condicion
print("### \n")
print(df[df['edad']>29])

nombre      Juan
edad          25
ciudad    Madrid
Name: 0, dtype: object
###

  nombre  edad   ciudad
0   Juan    25   Madrid
2  Pedro    35  Sevilla
###

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

ACCEDER A API

In [1]:
import pandas as pd
import requests

url = "https://api.open-meteo.com/v1/forecast"

params = {
    "latitude": -12.04,
    "longitude": -77.04,
    "hourly": "temperature_2m",
    "timezone": "America/Lima",
}

data = requests.get(url, params= params).json() # Pedir la data

df = pd.DataFrame(data["hourly"]) # Convertir

df.head() # usar

               time  temperature_2m
0  2026-10-09T00:00            21.8
1  2026-10-09T01:00            21.4
2  2026-10-09T02:00            21.2
3  2026-10-09T03:00            21.1
4  2026-10-09T04:00            20.9

In [2]:
url = "https://www.alphavantage.co/query"

params = {
    "function": "TIME_SERIES_DAILY",
    "symbol": "IBM",
    "apikey": "demo",        # reemplazar por tu clave
}

data = requests.get(url, params=params).json()
df = pd.DataFrame(data["Time Series (Daily)"]).T

df.head()

             1. open   2. high    3. low  4. close 5. volume
2026-10-09  225.8700  228.7600  224.0501  227.0950   3349059
2026-10-08  220.1500  227.3050  217.7950  226.6100   8929853
2026-10-07  221.9000  222.4100  218.7900  220.5100   3895497
2026-10-06  222.7100  224.5100  221.0000  221.2900   3938659
2026-10-05  222.3000  222.8800  220.3000  221.5800   6318079