# ETL

In [6]:
# Se importa la biblioteca 'pandas' para manipulacion y analisis en tablas
import pandas as pd
# Se importa la biblioteca 'sqlalchemy' para conectar y gestionar base de datos
import sqlalchemy as db
# Se importa la funcion 'text' de sqlalchemy para construir consultas SQL
from sqlalchemy import text

In [7]:
# Crear un motor de BD
engine = db.create_engine(
    "mysql+mysqlconnector://root:root@127.0.0.1:3310/db_movies_netflix_transact"
)

conn = engine.connect()

# CARGAR DIMENSION

In [8]:
query = """
SELECT 
    movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate, 
    gender.name as gender , person.name as participantName, participant.participantRole as roleparticipant 
FROM movie 
INNER JOIN participant 
ON movie.movieID=participant.movieID
INNER JOIN person
ON person.personID = participant.personID
INNER JOIN movie_gender 
ON movie.movieID = movie_gender.movieID
INNER JOIN gender 
ON movie_gender.genderID = gender.genderID
"""

In [11]:
# con pandas voy a leer los resultados del query

movies_data = pd.read_sql(query, con=conn)

movies_data["movieID"] = movies_data["movieID"].astype("int")

movies_data

,movieID,title,releaseDate,gender,participantName,roleparticipant
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director

In [14]:
# Cargar la informacion de premios
movies_awards = pd.read_csv("./data/Awards_movie.csv")

#Convertir el MovieId a int

movies_awards["movieID"] = movies_awards["movieID"].astype("int")

#renombrar los campos

movies_awards.rename(columns={"Aware":"Award"}, inplace=True)

movies_awards

    movieID  IdAward   Award
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar

In [16]:
#Unir las dos tablas o fuentes de datpos

movie_data = pd.merge( movies_data, movies_awards, left_on="movieID", right_on="movieID")

#Tranbsformaciones Finales

movie_data = movie_data.rename(columns = {'releaseDate':'releaseMovie', 'Award':'awardMovie'})

#Eliminar un campo

movie_data = movie_data.drop(columns =['IdAward'])

movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,Grammy

In [18]:
# Crear el motor y conexiones de dw_netflix
# Crear un motor de BD

engine_dw = db.create_engine(
    "mysql+mysqlconnector://root:root@127.0.0.1:3310/dw_netflix"
)

conn_dw = engine_dw.connect()

In [21]:
#Insertamos los valores

movie_data.to_sql('dimMovie', conn_dw, if_exists='append', index=False)

-1

# Dimension Users

In [23]:
# Cargar la informacion de Usuario

users = pd.read_csv("./data/users.csv", sep = '|')

users.head()

    idUser     username    country subscription
0  1002331      user123        USA      Premium
1  1002332  gamerGirl97     Canada        Basic
2  1002333   techMaster         UK      Premium
3  1002334    soccerFan     Brazil        Basic
4  1002335    travelBug  Australia      Premium

In [25]:
# Renombrar las columnas 

users = users.rename(columns= {'idUser':'userID'})

users.head()

    userID     username    country subscription
0  1002331      user123        USA      Premium
1  1002332  gamerGirl97     Canada        Basic
2  1002333   techMaster         UK      Premium
3  1002334    soccerFan     Brazil        Basic
4  1002335    travelBug  Australia      Premium

In [26]:
# Cargar al DW

users.to_sql('dimUser', conn_dw, if_exists='append', index=False)

-1

# FactWhats

In [27]:
# Cargar la lista de Usuarios

users_id = users['userID']

# Cargar la lista de peliculas

movies_id = movie_data['movieID']

In [29]:
users_id.head()

0    1002331
1    1002332
2    1002333
3    1002334
4    1002335
Name: userID, dtype: int64

In [30]:
movies_id.head()

0    80192187
1    80210920
2    81157374
Name: movieID, dtype: int64

In [32]:
# Cruce de los id

whatchs_data = pd.merge(users_id, movies_id, how='cross')

whatchs_data.head()

    userID   movieID
0  1002331  80192187
1  1002331  80210920
2  1002331  81157374
3  1002332  80192187
4  1002332  80210920

In [33]:
import random
from datetime import datetime, timedelta

def gen_rating():
    # Generar un número aleatorio entre 0 y 5 con 1 solo decimal
    numero_aleatorio = round(random.uniform(0, 5), 1)
    # Mostrar el número aleatorio
    return numero_aleatorio

def gen_timestamp():
    # Generar un timestamp aleatorio dentro de un rango específico
    start_date = datetime(2024, 1, 15)
    end_date = datetime(2024, 4, 6)

    # Calcular un valor aleatorio entre start_date y end_date
    random_date = start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))

    # Mostrar el timestamp aleatorio
    return random_date

In [35]:
# Agregar el campo de rating
whatchs_data['rating'] = whatchs_data['movieID'].apply(lambda x: gen_rating())

# Agregar o generar fechas
whatchs_data['timestamp'] = whatchs_data['movieID'].apply(lambda x: gen_timestamp())

whatchs_data.head()

    userID   movieID  rating           timestamp
0  1002331  80192187     0.7 2024-02-15 17:02:00
1  1002331  80210920     4.0 2024-03-09 03:54:33
2  1002331  81157374     0.8 2024-03-06 22:52:20
3  1002332  80192187     2.0 2024-01-20 02:52:22
4  1002332  80210920     4.6 2024-03-06 21:12:45

In [37]:
# Cargar la tabla

whatchs_data.to_sql('FactWatchs', conn_dw, if_exists='append', index=False)

-1